name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        # password: ${{secrets.GITHUB_TOKEN}}
        password: ${{ secrets.CICD_TOKEN }}
    - name: Build the Docker image
      env:
        GITHUB_SHA: ${{vars.GITHUB_SHA}}
        ACTOR: ${{github.actor}}  
        REPONAME: ${{ github.event.repository.name }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
      run: |
        image_tag="ghcr.io/$(echo $ACTOR | tr '[:upper:]' '[:lower:]')/$(echo imageBuilder | tr '[:upper:]' '[:lower:]'):$GITHUB_SHA"
        echo $image_tag
        docker build . --file flutter/Dockerfile --tag $image_tag
        docker push $image_tag
       
